version: "2"
services:
  backend:
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - mongo
    env_file:
      - ./variables.env
    environment:
    - NODE_ENV=production

  mongo:
    image: mongo
    ports:
    - "27017:27017"